name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CUDA_VISIBLE_DEVICES: ''  # explicitly disable GPU access
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl bc bison flex libelf-dev libssl-dev qemu-system-x86 apk-tools
      - name: Build kernel, initramfs and boot test (CPU-only)
        run: |
          ./build/build_ariannacore.sh --clean --test-qemu
      - name: Build alpine-conf scripts
        run: make -C for-codex-alpine-conf
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pytest -q
